### ISSUE TITLE
com.oculus.appsavety is enabled...

### ISSUE THREAD

**Issue by MerlinBlatterer** [basti564/Oculess#45] opened 2022-04-20 19:37 UTC
should it be disabled?
What does it do?

**Comment by raykai** [comment] 2022-05-01 15:23
I would also like to know what com.oculus.appsavety does.

**Comment by basti564** [comment] 2022-05-25 18:10
This is a duplicate of issue #5 AppSafety has not been able to be disabled for a long time, but I'm working on a fix. Currently the alternative to disabling it with Oculess would be to use an app specific firewall like [Netguard](https://netguard.me/) to prevent it from sending any data. If I remember correctly from last looking at it, its function is to verify the legitimacy of Apps and DLCs, so at best Meta is able to see whether your games are owned legitimately or not and which apps you have on your device. I hope this helps!

**Closed as completed by basti564** 2022-05-25 18:10 UTC
Labels: duplicate
