### ISSUE TITLE
v32: Not allowed to set the device owner 

### ISSUE THREAD

**Issue by gulopbr** [basti564/Oculess#7] opened 2021-04-20 15:16 UTC
After manually sideloading update v28, the command `adb shell dpm set-device-owner com.bos.oculess/.DevAdminReceiver`
returns the following error log. No multi accounts being used, it worked fine in v27.

> Error: Command failed: "C:\Users\gulop\AppData\Roaming\SideQuest\platform-tools\adb.exe" -s ********* shell dpm set-device-owner com.bos.oculess/.DevAdminReceiver java.lang.IllegalStateException: Not allowed to set the device owner because there are already some accounts on the device at android.os.Parcel.createException(Parcel.java:2079) at android.os.Parcel.readException(Parcel.java:2039) at android.os.Parcel.readException(Parcel.java:1987) at android.app.admin.IDevicePolicyManager$Stub$Proxy.setDeviceOwner(IDevicePolicyManager.java:8392) at com.android.commands.dpm.Dpm.runSetDeviceOwner(Dpm.java:203) at com.android.commands.dpm.Dpm.onRun(Dpm.java:115) at com.android.internal.os.BaseCommand.run(BaseCommand.java:65) at com.android.internal.os.BaseCommand.run(BaseCommand.java:49) at com.android.commands.dpm.Dpm.main(Dpm.java:41) at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method) at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:338) Caused by: android.os.RemoteException: Remote stack trace: at com.android.server.devicepolicy.DevicePolicyManagerService.enforceCanSetDeviceOwnerLocked(DevicePolicyManagerService.java:8652) at com.android.server.devicepolicy.DevicePolicyManagerService.setDeviceOwner(DevicePolicyManagerService.java:7821) at android.app.admin.IDevicePolicyManager$Stub.onTransact(IDevicePolicyManager.java:3270) at android.os.Binder.execTransactInternal(Binder.java:1021) at android.os.Binder.execTransact(Binder.java:994)

**Comment by coggy9** [comment] 2021-04-20 22:00
Maybe Facebook made dummy Android accounts to prevent Oculess from working? What do you get when you run `adb shell pm list users` ?

I only see myself, but I installed Oculess on v27, sideloaded 28, and I think Oculess is still the device owner, as this is what I get when running the same command. If it's still the owner, it looks like it'll need to be set up before v28 is installed for now.

```
127|hollywood:/ $ dpm set-device-owner com.bos.oculess/.DevAdminReceiver
java.lang.IllegalStateException: Trying to set the device owner, but device owner is already set.
        at android.os.Parcel.createException(Parcel.java:2079)
        at android.os.Parcel.readException(Parcel.java:2039)
        at android.os.Parcel.readException(Parcel.java:1987)
        at android.app.admin.IDevicePolicyManager$Stub$Proxy.setDeviceOwner(IDevicePolicyManager.java:8392)
        at com.android.commands.dpm.Dpm.runSetDeviceOwner(Dpm.java:203)
        at com.android.commands.dpm.Dpm.onRun(Dpm.java:115)
        at com.android.internal.os.BaseCommand.run(BaseCommand.java:65)
        at com.android.internal.os.BaseCommand.run(BaseCommand.java:49)
        at com.android.commands.dpm.Dpm.main(Dpm.java:41)
        at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
        at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:338)
Caused by: android.os.RemoteException: Remote stack trace:
        at com.android.server.devicepolicy.DevicePolicyManagerService.enforceCanSetDeviceOwnerLocked(DevicePolicyManagerService.java:8636)
        at com.android.server.devicepolicy.DevicePolicyManagerService.setDeviceOwner(DevicePolicyManagerService.java:7821)
        at android.app.admin.IDevicePolicyManager$Stub.onTransact(IDevicePolicyManager.java:3270)
        at android.os.Binder.execTransactInternal(Binder.java:1021)
        at android.os.Binder.execTransact(Binder.java:994)
```

**Comment by skaibaster** [comment] 2021-04-20 23:06
> Maybe Facebook made dummy Android accounts to prevent Oculess from working? What do you get when you run `adb shell pm list users` ?
> 
> I only see myself, but I installed Oculess on v27, sideloaded 28, and I think Oculess is still the device owner, as this is what I get when running the same command. If it's still the owner, it looks like it'll need to be set up before v28 is installed for now.
> 
> ```
> 127|hollywood:/ $ dpm set-device-owner com.bos.oculess/.DevAdminReceiver
> java.lang.IllegalStateException: Trying to set the device owner, but device owner is already set.
>         at android.os.Parcel.createException(Parcel.java:2079)
>         at android.os.Parcel.readException(Parcel.java:2039)
>         at android.os.Parcel.readException(Parcel.java:1987)
>         at android.app.admin.IDevicePolicyManager$Stub$Proxy.setDeviceOwner(IDevicePolicyManager.java:8392)
>         at com.android.commands.dpm.Dpm.runSetDeviceOwner(Dpm.java:203)
>         at com.android.commands.dpm.Dpm.onRun(Dpm.java:115)
>         at com.android.internal.os.BaseCommand.run(BaseCommand.java:65)
>         at com.android.internal.os.BaseCommand.run(BaseCommand.java:49)
>         at com.android.commands.dpm.Dpm.main(Dpm.java:41)
>         at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
>         at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:338)
> Caused by: android.os.RemoteException: Remote stack trace:
>         at com.android.server.devicepolicy.DevicePolicyManagerService.enforceCanSetDeviceOwnerLocked(DevicePolicyManagerService.java:8636)
>         at com.android.server.devicepolicy.DevicePolicyManagerService.setDeviceOwner(DevicePolicyManagerService.java:7821)
>         at android.app.admin.IDevicePolicyManager$Stub.onTransact(IDevicePolicyManager.java:3270)
>         at android.os.Binder.execTransactInternal(Binder.java:1021)
>         at android.os.Binder.execTransact(Binder.java:994)
> ```

`adb shell pm list users` This command returns only one user, so no dummy accounts.

**Comment by basti564** [comment] 2021-04-20 23:46
> After manually sideloading update v28, the command `adb shell dpm set-device-owner com.bos.oculess/.DevAdminReceiver`
> returns the following error log. No multi accounts being used, it worked fine in v27.
> 
> > Error: Command failed: "C:\Users\gulop\AppData\Roaming\SideQuest\platform-tools\adb.exe" -s ********* shell dpm set-device-owner com.bos.oculess/.DevAdminReceiver java.lang.IllegalStateException: Not allowed to set the device owner because there are already some accounts on the device at android.os.Parcel.createException(Parcel.java:2079) at android.os.Parcel.readException(Parcel.java:2039) at android.os.Parcel.readException(Parcel.java:1987) at android.app.admin.IDevicePolicyManager$Stub$Proxy.setDeviceOwner(IDevicePolicyManager.java:8392) at com.android.commands.dpm.Dpm.runSetDeviceOwner(Dpm.java:203) at com.android.commands.dpm.Dpm.onRun(Dpm.java:115) at com.android.internal.os.BaseCommand.run(BaseCommand.java:65) at com.android.internal.os.BaseCommand.run(BaseCommand.java:49) at com.android.commands.dpm.Dpm.main(Dpm.java:41) at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method) at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:338) Caused by: android.os.RemoteException: Remote stack trace: at com.android.server.devicepolicy.DevicePolicyManagerService.enforceCanSetDeviceOwnerLocked(DevicePolicyManagerService.java:8652) at com.android.server.devicepolicy.DevicePolicyManagerService.setDeviceOwner(DevicePolicyManagerService.java:7821) at android.app.admin.IDevicePolicyManager$Stub.onTransact(IDevicePolicyManager.java:3270) at android.os.Binder.execTransactInternal(Binder.java:1021) at android.os.Binder.execTransact(Binder.java:994)

Can you please describe what you have done?
Did you have Oculess set up on v27 and then update to v28? If yes there should not be a need to run the command again

**Comment by basti564** [comment] 2021-04-20 23:49
> Maybe Facebook made dummy Android accounts to prevent Oculess from working? What do you get when you run `adb shell pm list users` ?
> 
> I only see myself, but I installed Oculess on v27, sideloaded 28, and I think Oculess is still the device owner, as this is what I get when running the same command. If it's still the owner, it looks like it'll need to be set up before v28 is installed for now.
> 
> ```
> 127|hollywood:/ $ dpm set-device-owner com.bos.oculess/.DevAdminReceiver
> java.lang.IllegalStateException: Trying to set the device owner, but device owner is already set.
>         at android.os.Parcel.createException(Parcel.java:2079)
>         at android.os.Parcel.readException(Parcel.java:2039)
>         at android.os.Parcel.readException(Parcel.java:1987)
>         at android.app.admin.IDevicePolicyManager$Stub$Proxy.setDeviceOwner(IDevicePolicyManager.java:8392)
>         at com.android.commands.dpm.Dpm.runSetDeviceOwner(Dpm.java:203)
>         at com.android.commands.dpm.Dpm.onRun(Dpm.java:115)
>         at com.android.internal.os.BaseCommand.run(BaseCommand.java:65)
>         at com.android.internal.os.BaseCommand.run(BaseCommand.java:49)
>         at com.android.commands.dpm.Dpm.main(Dpm.java:41)
>         at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
>         at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:338)
> Caused by: android.os.RemoteException: Remote stack trace:
>         at com.android.server.devicepolicy.DevicePolicyManagerService.enforceCanSetDeviceOwnerLocked(DevicePolicyManagerService.java:8636)
>         at com.android.server.devicepolicy.DevicePolicyManagerService.setDeviceOwner(DevicePolicyManagerService.java:7821)
>         at android.app.admin.IDevicePolicyManager$Stub.onTransact(IDevicePolicyManager.java:3270)
>         at android.os.Binder.execTransactInternal(Binder.java:1021)
>         at android.os.Binder.execTransact(Binder.java:994)
> ```

Nope, they did not make hidden user accounts. Setting Oculess as device owner should still work on v28. The problem is that a bunch of things can cause the account error to occur and they are not necessarily related to the multi-user setup. The only fix right now is a factory reset :/

**Comment by basti564** [comment] 2021-04-21 14:23
Okay, I factory reset my Quest 2 and I also get the error "Not allowed to set the device owner because there are already some accounts on the device" It seems like removing telemetry won't work on v28 anymore :(

**Comment by basti564** [comment] 2021-04-21 14:42
edbfc48f477d183f742d336cb48877d6c8c580cf

**Comment by xieve** [comment] 2021-07-12 11:32
Works on v30 if you enable "Multiple Accounts" under Experimental Settings

**Comment by basti564** [comment] 2021-07-13 16:57
> Works on v30 if you enable "Multiple Accounts" under Experimental Settings

I never enabled "Multiple Accounts" on my device. On v30 it worked after I disabled the device admin. I can check if enabling "Multiple Accounts" works for me later.

**Comment by xieve** [comment] 2021-07-13 17:33
I didn't test this without multiple accounts enabled so far

**Comment by mastercreeper66** [comment] 2021-08-29 13:54
Not allowed to set the device owner on v32

**Comment by basti564** [comment] 2021-10-03 01:32
Fixed in release v1.2
just use the REMOVE ACCOUNTS function first and remove all accounts before entering the command :)

**Closed by basti564** 2021-10-03 01:32 UTC
Labels: bug

**Comment by lzgmc** [comment] 2021-12-04 07:27
It seems like the ability to set the device owner was patched in the latest v35 update, even after using the REMOVE ACCOUNTS function in Oculess. After factory resetting while on the latest update, sideloading Oculess, and removing all accounts, this is what happens when you try to set the device owner:
`
$ adb shell dpm set-device-owner com.bos.oculess/.DevAdminReceiver
java.lang.IllegalStateException: Not allowed to set the device owner because there are already some accounts on the device
	at android.os.Parcel.createException(Parcel.java:2046)
	at android.os.Parcel.readException(Parcel.java:2006)
	at android.os.Parcel.readException(Parcel.java:1954)
	at android.app.admin.IDevicePolicyManager$Stub$Proxy.setDeviceOwner(IDevicePolicyManager.java:8392)
	at com.android.commands.dpm.Dpm.runSetDeviceOwner(Dpm.java:203)
	at com.android.commands.dpm.Dpm.onRun(Dpm.java:115)
	at com.android.internal.os.BaseCommand.run(BaseCommand.java:65)
	at com.android.internal.os.BaseCommand.run(BaseCommand.java:49)
	at com.android.commands.dpm.Dpm.main(Dpm.java:41)
	at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
	at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:338)
Caused by: android.os.RemoteException: Remote stack trace:
	at com.android.server.devicepolicy.DevicePolicyManagerService.enforceCanSetDeviceOwnerLocked(DevicePolicyManagerService.java:8653)
	at com.android.server.devicepolicy.DevicePolicyManagerService.setDeviceOwner(DevicePolicyManagerService.java:7822)
	at android.app.admin.IDevicePolicyManager$Stub.onTransact(IDevicePolicyManager.java:3270)
	at android.os.Binder.execTransactInternal(Binder.java:1021)
	at android.os.Binder.execTransact(Binder.java:994)
`
This happens even when there are no accounts listed in the Settings menu after removing them. I've also tried disconnecting the headset from the internet and trying again, but the issue persists. FWIW, this was the update that took the multiple accounts function out of the Experimental Features tab in Settings.

**Comment by exodious** [comment] 2021-12-04 16:46
I have v35 and it worked for me. Not sure if the fact that I had to do a factory reset because the controllers wouldn't pair makes a difference.

**Comment by MaGiXieN** [comment] 2022-02-27 14:22
I have exactly the same problem on all my headsets (Quest 2). 

"C:\Users\myaccount\AppData\Roaming\SideQuest\platform-tools\adb.exe" -s 192.168.0.181:5555 shell dpm set-device-owner com.bos.oculess/.DevAdminReceiver java.lang.IllegalStateException: **Not allowed to set the device owner because there are already some accounts on the device** at android.os.Parcel.createException(Parcel.java:2046) at android.os.Parcel.readException(Parcel.java:2006) at android.os.Parcel.readException(Parcel.java:1954) at android.app.admin.IDevicePolicyManager$Stub$Proxy.setDeviceOwner(IDevicePolicyManager.java:8392) at com.android.commands.dpm.Dpm.runSetDeviceOwner(Dpm.java:203) at com.android.commands.dpm.Dpm.onRun(Dpm.java:115) at com.android.internal.os.BaseCommand.run(BaseCommand.java:65) at com.android.internal.os.BaseCommand.run(BaseCommand.java:49) at com.android.commands.dpm.Dpm.main(Dpm.java:41) at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method) at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:338) Caused by: android.os.RemoteException: Remote stack trace: at com.android.server.devicepolicy.DevicePolicyManagerService.enforceCanSetDeviceOwnerLocked(DevicePolicyManagerService.java:8653) at com.android.server.devicepolicy.DevicePolicyManagerService.setDeviceOwner(DevicePolicyManagerService.java:7822) at android.app.admin.IDevicePolicyManager$Stub.onTransact(IDevicePolicyManager.java:3270) at android.os.Binder.execTransactInternal(Binder.java:1021) at android.os.Binder.execTransact(Binder.java:994)

**Comment by SaharSionov** [comment] 2024-04-17 12:23
adb shell dpm set-device-owner com.bos.oculess/.DevAdminReceiver
